// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package govue

var _ = IntWrap(asset{Name: "base.amber", Content: "" +
	"extends 216672ef-bf07-400f-9eb7-9dcac1a2de0dfirst-base\n\nblock 216672ef-bf07-400f-9eb7-9dcac1a2de0dcomponents\n  import 216672ef-bf07-400f-9eb7-9dcac1a2de0dcmp-base" +
	"", etag: `"ElvV/Y1tjV4="`})
