// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package govue

var _ = IntWrap(asset{Name: "cmp-base.amber", Content: "" +
	"each $cmp in $.Components\n  #{ unescaped($.Template) }\n  #{ unescaped($.Script) }\n\n// script#tmp-footer[type=\"text/x-template\"]\n    span.text-xs-right[:v-html=\"value\"]\n\n// script#tmp-snack[type=\"text/x-template\"]\n  v-snackbar[v-model=\"shw\"][:timeout=\"timeout\"][:color=\"color\"]\n    span[v-html=\"text\"]\n    v-btn[text=\"\"][@click=\"shw=false\"][v-text=\"close\"]\n" +
	"", etag: `"NL+9srGjifs="`})
