// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package govue

var _ = IntWrap(asset{Name: "components.js", Content: "" +
	"GoVue = {\n    install(Vue, options) {\n    }\n}\n\nVue.use(GoVue)\nVue.use(Vuetify)" +
	"", etag: `"uJcO6hww98Q="`})
