// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package govue

var _ = IntWrap(asset{Name: "style.css", Content: "" +
	"  .wrap {\n    overflow: hidden;\n  }\n\n  .content {\n    width: 100000px;\n  }\n\n  .text {\n    animation-name: animation;\n    animation-timing-function: linear;\n    animation-iteration-count: infinite;\n    float: left;\n  }\n\n  .paused .text {\n    animation-play-state: paused\n  }\n\n  @keyframes animation {\n    0% { transform:translateX(0); }\n    100% { transform:translateX(-100%); }\n  }\n\n.marq { margin-right: 1em }\n" +
	"", etag: `"Qo39gkE7KgA="`})
