// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package govue

var _ = IntWrap(asset{Name: "vuescript.js", Content: "" +
	"if (!vm) {\nvm = new Vue({\n    el: '#app', vuetify: new Vuetify(),\n    // delimiters: ['${', '}'],\n    data() { return {\n    } },\n    filters: {\n    },\n    methods: {\n    },\n    watch: {\n    },\n    computed: {\n    },\n    created() {\n        var self = this\n        axios.defaults.headers.patch['Allow-Patch'] = 'application/json'\n        this.$vuetify.theme.dark = true\n        if (window.maticons) { this.maticons = Object.keys(window.maticons) }\n    },\n    mounted() { if (this.refresh) { this.refresh() } },\n})\n}\n" +
	"", etag: `"+P9fRfuS8lI="`})
